runtime: python27
api_version: 1
threadsafe: False

automatic_scaling:
  max_concurrent_requests: 2
  max_instances: 1
  max_idle_instances: 1

handlers:
- url: /vi/s
  static_dir: vi
- url: /static
  static_dir: static
  expiration: 10s
- url: /resources
  static_dir: server/resources
- url: /_tasks
  script: main.application
- url: /admin/user/getAuthMethod
  script: main.application
- url: /admin/.*
  script: main.application
- url: /vi.*
  script: main.application
- url: /favicon.ico
  static_files: static/meta/favicon.ico
  upload: favicon.ico
- url: /robots.txt
  static_files: static/meta/robots.txt
  upload: robots.txt
- url: /.*
  script: main.application

libraries:
- name: jinja2
  version: latest
- name: pytz
  version: latest

inbound_services:
- warmup

builtins:
- deferred: on
